service: michaelignat-web

image: michaelignat/web

servers:
  web:
    - 170.64.141.133

proxy:
  ssl: true
  host: michaelignat.com.au
  app_port: 3000
  healthcheck:
    path: /health
    interval: 7
    timeout: 49

registry:
  server: 151810432394.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
